<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CatsAssistant.Collector\CatsAssistant.Collector.csproj" />
    <ProjectReference Include="..\..\src\CatsAssistant.Store\CatsAssistant.Store.csproj" />
    <ProjectReference Include="..\..\src\CatsAssistant.Correlator\CatsAssistant.Correlator.csproj" />
    <ProjectReference Include="..\..\src\CatsAssistant.Connectors\CatsAssistant.Connectors.csproj" />
    <ProjectReference Include="..\..\src\CatsAssistant.Filler\CatsAssistant.Filler.csproj" />
    <ProjectReference Include="..\..\src\CatsAssistant.App\CatsAssistant.App.csproj" />
    <ProjectReference Include="..\..\src\CatsAssistant.Secrets\CatsAssistant.Secrets.csproj" />
  </ItemGroup>

</Project>
