<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CatsAssistant.Collector\CatsAssistant.Collector.csproj" />
    <ProjectReference Include="..\CatsAssistant.Store\CatsAssistant.Store.csproj" />
    <ProjectReference Include="..\CatsAssistant.Correlator\CatsAssistant.Correlator.csproj" />
    <ProjectReference Include="..\CatsAssistant.Connectors\CatsAssistant.Connectors.csproj" />
    <ProjectReference Include="..\CatsAssistant.Filler\CatsAssistant.Filler.csproj" />
    <ProjectReference Include="..\CatsAssistant.Secrets\CatsAssistant.Secrets.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2957.106" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\tray.ico</ApplicationIcon>
  </PropertyGroup>

</Project>
